Alpha-Omega bash script to setup tmux.
ao creates tmux sessions, windows, and pains for git repositories
I commonly work with as logical units.  Sessions supported are: ao,
bash, kjv, ssh, soup, vim, and work.

diff --git a/bin/ao b/bin/ao
--- a/bin/ao
+++ b/bin/ao
@@ -5,21 +5,86 @@
 #               Conference in the Cloud A Perl and Raku Conf
 #
 # https://www.youtube.com/watch?v=o7Dg1kmjhfQ&t=2428s
+#
+# Name: Alpha and Omega
+#   ao
+#
+# Use:
+#  ao kjv
+#
+# Argument:
+#  $1 tmux session name
+#
+# Note:
+#   1. A session is created or attached to.
+#   2. A new session is added if ao is used from with a tmux session.
 # ------------------------------------------------------------------------------
 
-if ! tmux has-session -t alpha; then
-  tmux new-session -c ${HOME}/git/dotfiles -n Dotfiles -s alpha -d
-  tmux send-keys -t alpha:1 'vim' Enter
+if [[ $# -eq 1 ]]; then
+  if ! tmux has-session -t $1 2>/dev/null; then
+    case $1 in
+      "ao")
+        tmux new-session -c ${HOME}/git/dotfiles/bin -n ao -s $1 -d
+        tmux send-keys   -t $1:1 'vim ao' Enter
+        ;;
+      "bash")
+        tmux new-session -c ${HOME}/git/dotfiles     -n dotfiles        -s $1 -d
+        tmux new-window  -c ${HOME}/git/dotfiles     -n bashrc          -t $1:2
+        tmux new-window  -c ${HOME}/git/dotfiles     -n bashrc-personal -t $1:3
+        tmux new-window  -c ${HOME}/git/dotfiles     -n bash_logout     -t $1:4
+        tmux new-window  -c ${HOME}/git/dotfiles     -n my_aliases      -t $1:5
+        tmux new-window  -c ${HOME}/git/dotfiles     -n my_completions  -t $1:6
+        tmux new-window  -c ${HOME}/git/dotfiles     -n my_exports      -t $1:7
+        tmux new-window  -c ${HOME}/git/dotfiles     -n my_functions    -t $1:8
+        tmux new-window  -c ${HOME}/git/dotfiles     -n my_paths        -t $1:9
+        tmux new-window  -c ${HOME}/git/dotfiles     -n my_prompt       -t $1:10
 
-  tmux new-window -c ${HOME}/git/scratchpad -n Scratchpad -t alpha:2
-  tmux split-window -t alpha:2 -h
-  tmux send-keys -t alpha:2.0 'ls -la' Enter
-  tmux send-keys -t alpha:2.1 'top' Enter
+        tmux send-keys   -t $1:2  'vim bashrc'          Enter
+        tmux send-keys   -t $1:3  'vim bashrc-personal' Enter
+        tmux send-keys   -t $1:4  'vim bash_logout'     Enter
+        tmux send-keys   -t $1:5  'vim my_aliases'      Enter
+        tmux send-keys   -t $1:6  'vim my_completions'  Enter
+        tmux send-keys   -t $1:7  'vim my_exports'      Enter
+        tmux send-keys   -t $1:8  'vim my_functions'    Enter
+        tmux send-keys   -t $1:9  'vim my_paths'        Enter
+        tmux send-keys   -t $1:10 'vim my_prompts'      Enter
 
-  tmux new-window -c ${HOME}/git/vim -n Vimmer -t alpha:3
-  tmux send-keys -t alpha:3 'vim plug.vim' Enter
+        tmux select-window -t $1:3
 
-  tmux new-window -c ${HOME}/git/kjv -n KJV -t alpha:4
-  tmux send-keys -t alpha:4 'kjv john' Enter
+        ;;
+      "kjv")
+        tmux new-session -c ${HOME}/git/kjv          -n kjv        -s $1 -d
+        ;;
+      "ssh")
+        tmux new-session -c ${HOME}/git/ssh          -n ssh        -t $1 -d
+        tmux new-window  -c ${HOME}/git/tmux         -n tmux       -t $1:2
+        tmux send-keys   -t $1:1 'vim -O config gitconfig' Enter
+        tmux send-keys   -t $1:2 'vim tmux.conf' Enter
+        ;;
+      "soup")
+        tmux new-session -c ${HOME}/git/amber        -n amber      -s $1 -d
+        tmux new-window  -c ${HOME}/git/autodoc      -n autodoc    -t $1:2
+        tmux new-window  -c ${HOME}/git/newdoc       -n newdoc     -t $1:3
+        ;;
+      "vim")
+        tmux new-session -c ${HOME}/git/vim          -n vim        -s $1 -d
+        tmux send-keys   -t $1:1 'vim plug.vim' Enter
+        ;;
+      "work")
+        tmux new-session -c ${HOME}/git/autodhf      -n autodhf    -s $1 -d
+        tmux new-window  -c ${HOME}/git/fk/otl       -n otl        -t $1:2
+        tmux new-window  -c ${HOME}/git/scratchpad   -n scratchpad -t $1:3
+        tmux send-keys   -t $1:2 'vim meeting-notes.otl' Enter
+        ;;
+      *)
+        echo "Session name $1 is not supported."
+        exit
+        ;;
+    esac
+  fi
+else
+  echo "Session name [ao|bash|kjv|ssh|soup|work] is required" && exit
 fi
-tmux attach -t alpha
+
+# Do not next TMUX
+[[ ! -n $TMUX ]] && tmux attach -t $1
