feat: Implement delete nvimapp.

diff --git a/bash/bin/nvims b/bash/bin/nvims
--- a/bash/bin/nvims
+++ b/bash/bin/nvims
@@ -1,5 +1,5 @@
 #!/bin/bash
-# {{{ Youtube: Demonstrate and checkoff items below.
+# {{{ Youtube: nvims: Demonstrate and checkoff items below.
 #
 #   1. [-] Open tmux-runner and send compand to run nvims executable script
 #   2. [-] Make a choice that is cloned
@@ -13,7 +13,7 @@
 # -- ----------------------------------------------------------------------- }}}
 # {{{ Define Neovim applications you want to experiment with.
 
-# Youtube: Review variables controlling output.
+# Youtube: nvims: Review variables controlling output.
 
 # File name that is overwritten with nvim appname aliases.
 readonly nvimAppNameFile="$BASHHOME"/nvim_appnames
@@ -45,7 +45,10 @@ dir=$(pwd)
 # -------------------------------------------------------------------------- }}}
 # {{{ Determine if a pull is needed.
 
+# Youtube: Demonstrate suppressed shellcheck error.
+# shellcheck disable=SC2120
 gitcheck() {
+
   # Git variables used to determine if a pull is needed.
   upstream=${1:-'@{u}'}
   local=$(git rev-parse @)
@@ -132,6 +135,35 @@ cloneRepository() {
 }
 
 # -------------------------------------------------------------------------- }}}
+# {{{ Recursively remove directory if present.
+
+removeDirIfPresent() {
+  if [[ -d "$1" ]]; then
+    echo "Removed $1"
+    rm -rf "$1"
+  fi
+}
+
+# -------------------------------------------------------------------------- }}}
+# {{{ Delete NvimApp from $HOME/.config directory
+
+deleteNvimApp() {
+  for fields in "${neovim_apps[@]}"; do
+    IFS=$'|' read -r alias url branch <<<"$fields"
+
+    alias="$(removeSpaces "$alias")"
+    if [[ "$1" == "$alias" ]]; then
+      echo "Deleting $alias if required."
+      removeDirIfPresent "$HOME"/.cache/"$alias"
+      removeDirIfPresent "$HOME"/.config/"$alias"
+      removeDirIfPresent "$HOME"/.local/share/"$alias"
+      removeDirIfPresent "$HOME"/.local/state/"$alias"
+      return
+    fi
+  done
+}
+
+# -------------------------------------------------------------------------- }}}
 # {{{ Run a command from another directory.
 
 runCommandFromDirectory() {
@@ -204,14 +236,41 @@ selectNeovimApp() {
 }
 
 # -------------------------------------------------------------------------- }}}
+# {{{ Get command line arguments.
+#     d : delete nvimapp selected
+#     h || invalid : display usage
+#     Normal nvims operation for anything else
+
+deleteNvimAppFlag=false
+while getopts 'dh' option; do
+  case "$option" in
+    d)
+      deleteNvimAppFlag=true
+      ;;
+    h)
+      echo "Usage: nvims [] [-d] [-h]"
+      exit 1
+      ;;
+    *)
+      printf "Usage: nvims [] [-d] [-h]\n"
+      exit 1
+      ;;
+  esac
+done
+
+# -- ----------------------------------------------------------------------- }}}
 # {{{ Main logic
 
 main() {
   buildNeovimAppArray
   writeAlisesFile
   choice="$(selectNeovimApp)"
-  cloneOrPullNvApp "$choice"
-  NVIM_APPNAME="$choice" nvim "$@"
+  if [[ $deleteNvimAppFlag == true ]]; then
+    deleteNvimApp "$choice"
+  else
+    cloneOrPullNvApp "$choice"
+    NVIM_APPNAME="$choice" nvim "$@"
+  fi
 }
 
 # -------------------------------------------------------------------------- }}}
